### ISSUE TITLE
bug: trivy randomly fails on CI

### ISSUE THREAD

**Issue by konrad-czarnota-ds** [deepsense-ai/ragbits#141]
From time to time I got failed CI build with linters stage that is caused by trivy. After re-runing it without changing anything it usually works. Logs: https://github.com/deepsense-ai/ragbits/actions/runs/11462036695/job/31892482009 .

**Comment by akonarski-ds** [comment]
Possible fix introduced in: https://github.com/deepsense-ai/ragbits/pull/87/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR56
