### ISSUE TITLE
feat: Install LiteLLM by default

### ISSUE THREAD

**Issue by ludwiktrammer** [deepsense-ai/ragbits#231]
Currently `ragbits` and `ragbits-core` are installed without installing LiteLLM (which requires explicitely installing `ragbits[litellm]`.

## Motivation
1. Ragbits requires LiteLLM to do almost anything useful (besides more advanced use cases of running local LLMs)
2. After #154, Ragbits comes pre configured with default LLM values which use LiteLLM. This currently leads to Ragbits not being able to use its own defaults by default ;)

## Steps
* `ragbits-core` should list LiteLLM as its direct dependency. 
* Conditional imports of `litellm` should be changes to regular imports
* Make `LiteLLM` available from the root `ragbits.core.llms` module
* Test that `LiteLLM` can imported without full path by `LLM.subclass_from_config` by adding test similar to `tests.unit.embeddings.test_from_config.test_subclass_from_config_default_path` to `tests.unit.llms.test_from_config` 
* All places that mention `ragbits[litellm]` in the documentation (e.g., Quickstart 1) should be adjusted accordingly

**Comment by mhordynski** [comment]
I totally agree! I'll go ahead and add it to https://github.com/deepsense-ai/ragbits/milestone/8. It looks like a great improvement for a small effort.
