### ISSUE TITLE
enabler: guardrails component design

### ISSUE THREAD

**Issue by akotyla** [deepsense-ai/ragbits#94]
We should think about introducing a guardrails component to manage multiple validation checks within the system. **We should focus on user input.**

All checkers should be stackable and run asynchronously.

Guardrails can include for example: safety checker to filter harmful or inappropriate content and relevance checker to verify if the user’s question aligns with the system's purpose and scope.

https://platform.openai.com/docs/models/moderation
https://github.com/unitaryai/detoxify

**Comment by micpst** [comment]
Resources that can be helpful:
 - https://www.llama.com/docs/model-cards-and-prompt-formats/llama-guard-3
 - https://www.lakera.ai/lakera-guard

**Comment by micpst** [comment]
Maybe we should also consider using an LLM proxy for this - https://docs.litellm.ai/docs/simple_proxy
